# Meta Data for SEO

## Homepage
title = "Band Horses"
titleSeparator = "|"
titleAddition = "The Official Website of Band Horses | Not Just Pictures!"
description = "The Band Horses are collectible musical NFTs. There are 4444 of them tapping on the blockchain."

## Open Graph
images = ["BNH-Site.png"]
ogLocale = "en_US"
titleHome = "Band Horses"

## Twitter Cards
twitterSite = "@bandhorsesNFT"
twitterCreator = "@bandhorsesNFT"

## JSON-LD
# schemaType = "Person"
schemaType = "Organization"
schemaName = "bandhorses"
schemaAuthor = "Band Horse"
schemaAuthorTwitter = "https://twitter.com/bandhorsesNFT"
schemaLocale = "en-US"
schemaLogo = "band-horses-logo.png"
schemaLogoWidth = 244
schemaLogoHeight = 90
schemaImage = "BNH-Site.png"
schemaImageWidth = 1366
schemaImageHeight = 768
schemaTwitter = "https://twitter.com/bandhorsesNFT"
schemaDiscord = "https://discord.com/invite/UyaJspUaSZ"
schemaInstagram = "https://www.instagram.com/bandhorses"

## Chrome Browser
themeColor = "#FEFBFC"

# Images
quality = 85
bgColor = "#FEFBFC"
landscapePhotoWidths = [900, 800, 700, 600, 500]
portraitPhotoWidths = [800, 700, 600, 500]
lqipWidth = "30x"
smallLimit = "360"

# Footer
footer = "ğŸµ ğŸ´ ğŸ¥ ğŸ¸ ğŸ” "

# Feed
copyRight = "ğŸµ ğŸ´ ğŸ¥ ğŸ¸ ğŸ”"

# Alert
alert = false
alertDismissable = true
alertText = "Early access to Band Horses NFT sale. <a class=\"alert-link\" href=\"https://form.jotform.com/220403084309042/\" target=\"_blank\" rel=\"noopener\">Get me listed â†’</a>"
